vandeWiel.c File Reference
#include <R.h>
#include <Rmath.h>
#include <Rdefines.h>
Classes
struct celW
Functions
double binomi (int m, int n)
celW ** reserveW (int a, int b)
void FreeW (int a, celW **W)
void initW (int a, int b, celW **W)
void mult (celW *tem, int a, int b, int rank, double *rs)
void plus (celW **W, celW *tempie, int a, int b, double tol)
void mymergesort (celW temptw, long tijd)
void fillcell (celW **W, int i1, int j1, int r, double *rs, double tol)
void mirrorW (celW **W, int ce, int bep, int start, double *rs)
void makeW (celW **W, int a, int b, int start, double *rs, double tol)
void cumulcoef (celW **W, int i1, int j1)
double numbersmall (int c, int b, double ob, celW **W1, celW **W2, double tol)
SEXP R_split_up_2sample (SEXP scores, SEXP m, SEXP obs, SEXP tol)
Detailed Description
Exact Distribution of Two-Sample Permutation Tests van de Wiel split-up Algorithm
Author: Mark van de Wiel (2001-2005) <m.a.v.d.wiel@TUE.nl> with modifications for R by Torsten Hothorn <Torsten.Hothorn@R-project.org>
Author
Author:
hothorn
Date
Date:
2009-10-30 18:34:34 +0100 (Fri, 30 Oct 2009)
Definition in file vandeWiel.c.
Function Documentation
double binomi (int m, int n)
Definition at line 37 of file vandeWiel.c.
Referenced by R_split_up_2sample(), and reserveW().
void cumulcoef (celW ** W, int i1, int j1)
Definition at line 316 of file vandeWiel.c.
References celW::c, and celW::length.
Referenced by R_split_up_2sample().
void fillcell (celW ** W, int i1, int j1, int r, double * rs, double tol)
Definition at line 211 of file vandeWiel.c.
References celW::c, celW::length, mult(), mymergesort(), plus(), and celW::x.
Referenced by makeW().
void FreeW (int a, celW ** W)
Definition at line 81 of file vandeWiel.c.
Referenced by R_split_up_2sample().
void initW (int a, int b, celW ** W)
Definition at line 91 of file vandeWiel.c.
References celW::c, celW::length, and celW::x.
Referenced by R_split_up_2sample().
void makeW (celW ** W, int a, int b, int start, double * rs, double tol)
Definition at line 281 of file vandeWiel.c.
References fillcell(), and mirrorW().
Referenced by R_split_up_2sample().
void mirrorW (celW ** W, int ce, int bep, int start, double * rs)
Definition at line 257 of file vandeWiel.c.
References celW::c, celW::length, and celW::x.
Referenced by makeW().
void mult (celW * tem, int a, int b, int rank, double * rs)
Definition at line 106 of file vandeWiel.c.
References celW::length.
Referenced by fillcell().
void mymergesort (celW temptw, long tijd)
Definition at line 159 of file vandeWiel.c.
References celW::c, celW::length, and celW::x.
Referenced by fillcell().
double numbersmall (int c, int b, double ob, celW ** W1, celW ** W2, double tol)
Definition at line 335 of file vandeWiel.c.
References celW::c, celW::length, and celW::x.
Referenced by R_split_up_2sample().
void plus (celW ** W, celW * tempie, int a, int b, double tol)
Definition at line 120 of file vandeWiel.c.
References celW::c, celW::length, and celW::x.
Referenced by fillcell().
SEXP R_split_up_2sample (SEXP scores, SEXP m, SEXP obs, SEXP tol)
Definition at line 377 of file vandeWiel.c.
References binomi(), cumulcoef(), FreeW(), initW(), makeW(), numbersmall(), and reserveW().
celW** reserveW (int a, int b)
Definition at line 51 of file vandeWiel.c.
References binomi(), celW::c, and celW::x.
Referenced by R_split_up_2sample().