.TH "src/ Directory Reference" 3 "17 Oct 2006" "coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ Directory Reference \- 
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCI_common.h\fP"
.br
.ti -1c
.RI "file \fBCIstuff.c\fP"
.br
.ti -1c
.RI "file \fBCIstuff.h\fP"
.br
.ti -1c
.RI "file \fBClasses.c\fP"
.br
.ti -1c
.RI "file \fBClasses.h\fP"
.br
.ti -1c
.RI "file \fBLinearStatistic.c\fP"
.br
.ti -1c
.RI "file \fBLinearStatistic.h\fP"
.br
.ti -1c
.RI "file \fBStreitbergRoehmel.c\fP"
.br
.ti -1c
.RI "file \fBvandeWiel.c\fP"
.br
.in -1c
