.TH "celW" 3 "17 Nov 2005" "coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
celW \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBlength\fP"
.br
.ti -1c
.RI "double * \fBc\fP"
.br
.ti -1c
.RI "double * \fBx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The probability distribution for the independent two sample problem.
.PP
REFERENCE
.PP
M.A. van de Wiel (2001). The split-up algorithm: a fast symbolic method for computing p-values of rank statistics, Computational Statistics, 16, 519-538. 
.PP
Definition at line 31 of file vandeWiel.c.
.SH "Member Data Documentation"
.PP 
.SS "double* \fBcelW::c\fP"
.PP
Definition at line 33 of file vandeWiel.c.
.PP
Referenced by cumulcoef(), fillcell(), initW(), mirrorW(), mymergesort(), numbersmall(), plus(), and reserveW().
.SS "long \fBcelW::length\fP"
.PP
Definition at line 32 of file vandeWiel.c.
.PP
Referenced by cumulcoef(), fillcell(), initW(), mirrorW(), mymergesort(), numbersmall(), and plus().
.SS "double* \fBcelW::x\fP"
.PP
Definition at line 34 of file vandeWiel.c.
.PP
Referenced by fillcell(), initW(), mirrorW(), mult(), mymergesort(), plus(), and reserveW().

.SH "Author"
.PP 
Generated automatically by Doxygen for coin from the source code.
