.TH "CIstuff.h" 3 "25 Aug 2006" "coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CIstuff.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBnrow\fP (SEXP x)"
.br
.ti -1c
.RI "int \fBncol\fP (SEXP x)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ncol (SEXP x)"
.PP
Definition at line 22 of file CIstuff.c.
.PP
Referenced by R_ExpectCovarInfluence(), R_ExpectCovarLinearStatistic(), R_kronecker(), R_LinearStatistic(), R_MonteCarloIndependenceTest(), and R_PermutedLinearStatistic().
.SS "int nrow (SEXP x)"
.PP
Definition at line 11 of file CIstuff.c.
.PP
Referenced by R_ExpectCovarInfluence(), R_ExpectCovarLinearStatistic(), R_kronecker(), R_LinearStatistic(), R_MonteCarloIndependenceTest(), and R_PermutedLinearStatistic().
.SH "Author"
.PP 
Generated automatically by Doxygen for coin from the source code.
