.TH "Classes.h" 3 "5 May 2008" "coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Classes.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "SEXP \fBcoin_expectationSym\fP"
.br
.ti -1c
.RI "SEXP \fBcoin_covarianceSym\fP"
.br
.ti -1c
.RI "SEXP \fBcoin_sumweightsSym\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "SEXP \fBcoin_covarianceSym\fP"
.PP
Definition at line 12 of file Classes.c.
.SS "SEXP \fBcoin_expectationSym\fP"
.PP
Definition at line 12 of file Classes.c.
.SS "SEXP \fBcoin_sumweightsSym\fP"
.PP
Definition at line 12 of file Classes.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for coin from the source code.
