.TH "Classes.h" 3 "7 Sep 2006" "coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Classes.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "SEXP \fBCI_expectationSym\fP"
.br
.ti -1c
.RI "SEXP \fBCI_covarianceSym\fP"
.br
.ti -1c
.RI "SEXP \fBCI_sumweightsSym\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "SEXP \fBCI_covarianceSym\fP"
.PP
Definition at line 12 of file Classes.c.
.PP
Referenced by C_ExpectCovarInfluence(), C_ExpectCovarLinearStatistic(), coin_init(), R_ExpectCovarInfluence(), and R_ExpectCovarLinearStatistic().
.SS "SEXP \fBCI_expectationSym\fP"
.PP
Definition at line 12 of file Classes.c.
.PP
Referenced by C_ExpectCovarInfluence(), C_ExpectCovarLinearStatistic(), coin_init(), R_ExpectCovarInfluence(), and R_ExpectCovarLinearStatistic().
.SS "SEXP \fBCI_sumweightsSym\fP"
.PP
Definition at line 12 of file Classes.c.
.PP
Referenced by C_ExpectCovarInfluence(), C_ExpectCovarLinearStatistic(), coin_init(), and R_ExpectCovarInfluence().
.SH "Author"
.PP 
Generated automatically by Doxygen for coin from the source code.
