.TH "Classes.c" 3 "28 Jul 2005" "coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Classes.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CI_common.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "SEXP \fBcoin_init\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "SEXP \fBCI_expectationSym\fP"
.br
.ti -1c
.RI "SEXP \fBCI_covarianceSym\fP"
.br
.ti -1c
.RI "SEXP \fBCI_sumweightsSym\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
S4 classes
.PP
\fBAuthor:\fP
.RS 4
\fBAuthor\fP.RS 4
hothorn 
.RE
.PP
.RE
.PP
\fBDate:\fP
.RS 4
\fBDate\fP.RS 4
2005/02/10 14:54:09 
.RE
.PP
.RE
.PP

.PP
Definition in file \fBClasses.c\fP.
.SH "Function Documentation"
.PP 
.SS "SEXP coin_init (void)"
.PP
Definition at line 16 of file Classes.c.
.PP
References CI_covarianceSym, CI_expectationSym, and CI_sumweightsSym.
.SH "Variable Documentation"
.PP 
.SS "SEXP \fBCI_covarianceSym\fP"
.PP
Definition at line 12 of file Classes.c.
.PP
Referenced by C_ExpectCovarInfluence(), C_ExpectCovarLinearStatistic(), coin_init(), R_ExpectCovarInfluence(), and R_ExpectCovarLinearStatistic().
.SS "SEXP \fBCI_expectationSym\fP"
.PP
Definition at line 12 of file Classes.c.
.PP
Referenced by C_ExpectCovarInfluence(), C_ExpectCovarLinearStatistic(), coin_init(), R_ExpectCovarInfluence(), and R_ExpectCovarLinearStatistic().
.SS "SEXP \fBCI_sumweightsSym\fP"
.PP
Definition at line 12 of file Classes.c.
.PP
Referenced by C_ExpectCovarInfluence(), C_ExpectCovarLinearStatistic(), coin_init(), and R_ExpectCovarInfluence().
.SH "Author"
.PP 
Generated automatically by Doxygen for coin from the source code.
