.TH "coin_common.h" 3 "24 Apr 2007" "coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coin_common.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <R.h>\fP
.br
\fC#include <Rmath.h>\fP
.br
\fC#include <Rinternals.h>\fP
.br
\fC#include <Rdefines.h>\fP
.br
\fC#include <R_ext/Applic.h>\fP
.br
\fC#include 'Classes.h'\fP
.br
\fC#include 'LinearStatistic.h'\fP
.br
\fC#include 'Helpers.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for coin from the source code.
