.TH "LinearStatistic.c" 3 "5 May 2008" "coin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LinearStatistic.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'coin_common.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBC_kronecker\fP (const double *A, const int m, const int n, const double *B, const int r, const int s, double *ans)"
.br
.ti -1c
.RI "SEXP \fBR_kronecker\fP (SEXP A, SEXP B)"
.br
.ti -1c
.RI "void \fBC_ExpectCovarInfluence\fP (const double *y, const int q, const double *weights, const int n, SEXP ans)"
.br
.ti -1c
.RI "SEXP \fBR_ExpectCovarInfluence\fP (SEXP y, SEXP weights)"
.br
.ti -1c
.RI "void \fBC_ExpectCovarLinearStatistic\fP (const double *x, const int p, const double *y, const int q, const double *weights, const int n, const SEXP expcovinf, SEXP ans)"
.br
.ti -1c
.RI "SEXP \fBR_ExpectCovarLinearStatistic\fP (SEXP x, SEXP y, SEXP weights, SEXP expcovinf)"
.br
.ti -1c
.RI "void \fBC_LinearStatistic\fP (const double *x, const int p, const double *y, const int q, const double *weights, const int n, double *ans)"
.br
.ti -1c
.RI "SEXP \fBR_LinearStatistic\fP (SEXP x, SEXP y, SEXP weights)"
.br
.ti -1c
.RI "void \fBC_PermutedLinearStatistic\fP (const double *x, const int p, const double *y, const int q, const int n, const int nperm, const int *indx, const int *perm, double *ans)"
.br
.ti -1c
.RI "SEXP \fBR_PermutedLinearStatistic\fP (SEXP x, SEXP y, SEXP indx, SEXP perm)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Linear statistics for conditional inference
.PP
\fBAuthor:\fP
.RS 4
\fBAuthor\fP.RS 4

.RE
.PP
.RE
.PP
\fBDate:\fP
.RS 4
\fBDate\fP.RS 4

.RE
.PP
.RE
.PP

.PP
Definition in file \fBLinearStatistic.c\fP.
.SH "Function Documentation"
.PP 
.SS "void C_ExpectCovarInfluence (const double * y, const int q, const double * weights, const int n, SEXP ans)"
.PP
Conditional expectation and covariance of the influence function
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIy\fP values of the influence function 
.br
\fIq\fP dimension of the influence function 
.br
\fIweights\fP case weights 
.br
\fIn\fP number of observations 
.br
\fIans\fP return value; an object of class `ExpectCovarInfluence' 
.RE
.PP

.PP
Definition at line 80 of file LinearStatistic.c.
.PP
References coin_covarianceSym, coin_expectationSym, and coin_sumweightsSym.
.PP
Referenced by R_ExpectCovarInfluence().
.SS "void C_ExpectCovarLinearStatistic (const double * x, const int p, const double * y, const int q, const double * weights, const int n, const SEXP expcovinf, SEXP ans)"
.PP
Conditional expectation and covariance of the a linear statistic
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP values of the transformation 
.br
\fIp\fP dimension of the transformation 
.br
\fIy\fP values of the influence function 
.br
\fIq\fP dimension of the influence function 
.br
\fIweights\fP case weights 
.br
\fIn\fP number of observations 
.br
\fIexpcovinf\fP an object of class `ExpectCovarInfluence' 
.br
\fIans\fP return value; an object of class `ExpectCovar' 
.RE
.PP

.PP
Definition at line 192 of file LinearStatistic.c.
.PP
References C_kronecker(), coin_covarianceSym, coin_expectationSym, and coin_sumweightsSym.
.PP
Referenced by R_ExpectCovarLinearStatistic().
.SS "void C_kronecker (const double * A, const int m, const int n, const double * B, const int r, const int s, double * ans)"
.PP
Computes the Kronecker product of two matrices
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIA\fP matrix 
.br
\fIm\fP nrow(A) 
.br
\fIn\fP ncol(A) 
.br
\fIB\fP matrix 
.br
\fIr\fP nrow(B) 
.br
\fIs\fP ncol(B) 
.br
\fIans\fP return value; a pointer to a REALSXP-vector of length (mr x ns) 
.RE
.PP

.PP
Definition at line 22 of file LinearStatistic.c.
.PP
Referenced by C_ExpectCovarLinearStatistic(), and R_kronecker().
.SS "void C_LinearStatistic (const double * x, const int p, const double * y, const int q, const double * weights, const int n, double * ans)"
.PP
Computes the linear statistic, formula (1) in the paper
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP values of the transformation 
.br
\fIp\fP dimension of the transformation 
.br
\fIy\fP values of the influence function 
.br
\fIq\fP dimension of the influence function 
.br
\fIweights\fP case weights 
.br
\fIn\fP number of observations 
.br
\fIans\fP return value; a pointer to a REALSXP-vector of length pq 
.RE
.PP

.PP
Definition at line 327 of file LinearStatistic.c.
.PP
Referenced by R_LinearStatistic().
.SS "void C_PermutedLinearStatistic (const double * x, const int p, const double * y, const int q, const int n, const int nperm, const int * indx, const int * perm, double * ans)"
.PP
Linear Statistic with permuted indices
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP values of the transformation 
.br
\fIp\fP dimension of the transformation 
.br
\fIy\fP values of the influence function 
.br
\fIq\fP dimension of the influence function 
.br
\fIn\fP number of observations 
.br
\fInperm\fP number of permutations 
.br
\fIindx\fP indices for the x-part 
.br
\fIperm\fP (permuted) indices for the y-part 
.br
\fIans\fP return value; a pointer to a REALSXP-vector of length pq 
.RE
.PP

.PP
Definition at line 409 of file LinearStatistic.c.
.PP
Referenced by R_MonteCarloIndependenceTest(), and R_PermutedLinearStatistic().
.SS "SEXP R_ExpectCovarInfluence (SEXP y, SEXP weights)"
.PP
R-interface to C_ExpectCovarInfluence
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIy\fP values of the influence function 
.br
\fIweights\fP case weights 
.RE
.PP

.PP
Definition at line 150 of file LinearStatistic.c.
.PP
References C_ExpectCovarInfluence(), coin_covarianceSym, coin_expectationSym, coin_sumweightsSym, ncol(), and nrow().
.SS "SEXP R_ExpectCovarLinearStatistic (SEXP x, SEXP y, SEXP weights, SEXP expcovinf)"
.PP
R-interface to C_ExpectCovarLinearStatistic
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP values of the transformation 
.br
\fIy\fP values of the influence function 
.br
\fIweights\fP case weights 
.br
\fIexpcovinf\fP an object of class `ExpectCovarInfluence' 
.RE
.PP

.PP
Definition at line 285 of file LinearStatistic.c.
.PP
References C_ExpectCovarLinearStatistic(), coin_covarianceSym, coin_expectationSym, ncol(), and nrow().
.SS "SEXP R_kronecker (SEXP A, SEXP B)"
.PP
R-interface to C_kronecker
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIA\fP matrix 
.br
\fIB\fP matrix 
.RE
.PP

.PP
Definition at line 51 of file LinearStatistic.c.
.PP
References C_kronecker(), ncol(), and nrow().
.SS "SEXP R_LinearStatistic (SEXP x, SEXP y, SEXP weights)"
.PP
R-interface to C_LinearStatistic 
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP values of the transformation 
.br
\fIy\fP values of the influence function 
.br
\fIweights\fP case weights 
.RE
.PP

.PP
Definition at line 363 of file LinearStatistic.c.
.PP
References C_LinearStatistic(), ncol(), and nrow().
.SS "SEXP R_PermutedLinearStatistic (SEXP x, SEXP y, SEXP indx, SEXP perm)"
.PP
Linear Statistic with permuted indices
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP values of the transformation 
.br
\fIy\fP values of the influence function 
.br
\fIindx\fP indices for the x-part 
.br
\fIperm\fP (permuted) indices for the y-part 
.RE
.PP

.PP
Definition at line 442 of file LinearStatistic.c.
.PP
References C_PermutedLinearStatistic(), ncol(), and nrow().
.SH "Author"
.PP 
Generated automatically by Doxygen for coin from the source code.
